CREATE TABLE IF NOT EXISTS PRODUCTS (
SNO TEXT PRIMARY KEY,
NAME_OF_THE_PRODUCT TEXT,
PRICE_OF_THE_PRODUCT INTEGER,
PRODUCT_COMPANY TEXT
);

INSERT INTO PRODUCTS ( SNO , NAME_OF_THE_PRODUCT , PRICE_OF_THE_PRODUCT , PRODUCT_COMPANY ) VALUES
( 'S1' , 'INTEL CORE I7' , '30,000' , 'INTEL' ),
( 'S2' , 'AMD RYZEN 7' , '25,000' , 'AMD' ),
( 'S3' , 'INTEL CORE I5' , '20,000' , 'INTEL' ),
( 'S4' , 'AMD RYZEN 5' , '15,000' , 'AMD' ),
( 'S5' , 'INTEL CORE I3' , '10,000' , 'INTEL' ),
( 'S6' , 'AMD RYZEN 3' , '5,000' , 'AMD' ),
( 'S7' , 'INTEL CORE I9' , '40,000' , 'INTEL' ),
( 'S8' , 'AMD RYZEN 9' , '35,000' , 'AMD' ),
( 'S9' , 'INTEL CORE I7' , '30,000' , 'INTEL' ),
( 'S10' , 'AMD RYZEN 7' , '25,000' , 'AMD' );

SELECT NAME_OF_THE_PRODUCT ,PRICE_OF_THE_PRODUCT
FROM PRODUCTS
WHERE PRICE_OF_THE_PRODUCT = (SELECT min(PRICE_OF_THE_PRODUCT) FROM PRODUCTS);
SELECT NAME_OF_THE_PRODUCT ,PRICE_OF_THE_PRODUCT
FROM PRODUCTS
WHERE PRICE_OF_THE_PRODUCT = (SELECT max(PRICE_OF_THE_PRODUCT) FROM PRODUCTS);
