CREATE TABLE SUPPLIER (
    SNO TEXT PRIMARY KEY,
    SNAME TEXT,
    STATUS INTEGER,
    CITY TEXT
);
INSERT INTO SUPPLIER (SNO, SNAME, STATUS, CITY) VALUES 
('S1', 'Smith', 20, 'London'),
('S2', 'Jones', 10, 'Paris'),
('S3', 'Blake', 30, 'Paris'),
('S4', 'Clark', 20, 'London'),
('S5', 'Adams', 30, 'Athens');

SELECT * FROM SUPPLIER;
SELECT SNAME, CITY FROM SUPPLIER;
SELECT * FROM SUPPLIER WHERE STATUS = 20;
SELECT * FROM SUPPLIER WHERE CITY = 'Paris';

INSERT INTO SUPPLIER (SNO,SNAME,CITY) VALUES 
("101", "SHORYA", "SURAT");
SELECT * FROM SUPPLIER;