CREATE TABLE IF NOT EXISTS NEW_EMPLOYEES (
  'SNO' INTEGER NOT NULL,
  'ID' INTEGER PRIMARY KEY AUTOINCREMENT,
  'NAME' TEXT NOT NULL,
  'AGE' INTEGER NOT NULL,
  'COMMUNICATION' INTEGER NOT NULL,
  'TECHNICAL_SKILLS' INTEGER NOT NULL,
  'LEADERSHIP' INTEGER NOT NULL,
  'TEAMWORK' INTEGER NOT NULL,
  'PROBLEM_SOLVING' INTEGER NOT NULL,
  'ADDRESS' TEXT NOT NULL
);

INSERT INTO NEW_EMPLOYEES (SNO, ID, NAME, AGE, COMMUNICATION, TECHNICAL_SKILLS, LEADERSHIP, TEAMWORK, PROBLEM_SOLVING, ADDRESS) VALUES 
(1, 1, 'Alice', 20, 85, 90, 78, 92, 88, 'NEW YORK'),
(2, 2, 'Bob', 22, 90, 80, 82, 85, 91, 'LOS ANGELES'),
(3, 3, 'Charlie', 19, 78, 88, 84, 90, 87,'INDIA'),
(4, 4, 'David', 21, 92, 85, 89, 91, 90,'HOUSTON'),
(5, 5, 'Eve', 20, 88, 91, 87, 89 ,92,'PHOENIX'),
(6, 6,'Frank',23 ,80 ,82 ,84 ,86 ,88 ,'PHILADELPHIA'),
(7 ,7 ,'Grace' ,19 ,95 ,90 ,92 ,94 ,96 ,'SAN ANTONIO'),
(8 ,8 ,'Heidi' ,22 ,82 ,85 ,88 ,90 ,91 ,'INDIA'),
(9 ,9 ,'Ivan' ,20 ,89 ,87 ,90 ,92 ,94 ,'DALLAS'),
(10 ,10 ,'Judy' ,21 ,91 ,88 ,89 ,93 ,95 ,'SAN JOSE');

SELECT COUNT(COMMUNICATION) AS TOTAL_EMPLOYEES FROM NEW_EMPLOYEES;
SELECT AVG(COMMUNICATION) AS AVERAGE_COMMUNICATION FROM NEW_EMPLOYEES;
SELECT SUM(COMMUNICATION) AS TOTAL_COMMUNICATION FROM NEW_EMPLOYEES;

SELECT COUNT(TECHNICAL_SKILLS) AS TOTAL_EMPLOYEES FROM NEW_EMPLOYEES;
SELECT AVG(TECHNICAL_SKILLS) AS AVERAGE_TECHNICAL_SKILLS FROM NEW_EMPLOYEES;
SELECT SUM(TECHNICAL_SKILLS) AS TOTAL_TECHNICAL_SKILLS FROM NEW_EMPLOYEES;

SELECT COUNT(LEADERSHIP) AS TOTAL_EMPLOYEES FROM NEW_EMPLOYEES;
SELECT AVG(LEADERSHIP) AS AVERAGE_LEADERSHIP FROM NEW_EMPLOYEES;
SELECT SUM(LEADERSHIP) AS TOTAL_LEADERSHIP FROM NEW_EMPLOYEES;

SELECT COUNT(TEAMWORK) AS TOTAL_EMPLOYEES FROM NEW_EMPLOYEES;
SELECT AVG(TEAMWORK) AS AVERAGE_TEAMWORK FROM NEW_EMPLOYEES;
SELECT SUM(TEAMWORK) AS TOTAL_TEAMWORK FROM NEW_EMPLOYEES;

SELECT COUNT(PROBLEM_SOLVING) AS TOTAL_EMPLOYEES FROM NEW_EMPLOYEES;
SELECT AVG(PROBLEM_SOLVING) AS AVERAGE_PROBLEM_SOLVING FROM NEW_EMPLOYEES;
SELECT SUM(PROBLEM_SOLVING) AS TOTAL_PROBLEM_SOLVING FROM NEW_EMPLOYEES;