CREATE TABLE IF NOT EXISTS NEW_STUDENTS (
  'SNO' INTEGER NOT NULL,
  'ID' INTEGER PRIMARY KEY AUTOINCREMENT,
  'NAME' TEXT NOT NULL,
  'AGE' INTEGER NOT NULL,
  'ENG_MARKS' INTEGER NOT NULL,
  'MATH_MARKS' INTEGER NOT NULL,
  'HINDI_MARKS' INTEGER NOT NULL,
  'SS_MARKS' INTEGER NOT NULL,
  'SCIENCE_MARKS' INTEGER NOT NULL,
  'ADDRESS' TEXT NOT NULL
);

INSERT INTO NEW_STUDENTS (SNO, ID, NAME, AGE, ENG_MARKS, MATH_MARKS, HINDI_MARKS, SS_MARKS, SCIENCE_MARKS, ADDRESS) VALUES 
(1, 1, 'Alice', 20, 85, 90, 78, 92, 88, 'NEW YORK'),
(2, 2, 'Bob', 22, 90, 80, 82, 85, 91, 'LOS ANGELES'),
(3, 3, 'Charlie', 19, 78, 88, 84, 90, 87,'INDIA'),
(4, 4, 'David', 21, 92, 85, 89, 91, 90,'HOUSTON'),
(5, 5, 'Eve', 20, 88, 91, 87, 89 ,92,'PHOENIX'),
(6, 6,'Frank',23 ,80 ,82 ,84 ,86 ,88 ,'PHILADELPHIA'),
(7 ,7 ,'Grace' ,19 ,95 ,90 ,92 ,94 ,96 ,'SAN ANTONIO'),
(8 ,8 ,'Heidi' ,22 ,82 ,85 ,88 ,90 ,91 ,'INDIA'),
(9 ,9 ,'Ivan' ,20 ,89 ,87 ,90 ,92 ,94 ,'DALLAS'),
(10 ,10 ,'Judy' ,21 ,91 ,88 ,89 ,93 ,95 ,'SAN JOSE');

SELECT COUNT(ENG_MARKS) AS TOTAL_STUDENTS FROM NEW_STUDENTS;
SELECT AVG(ENG_MARKS) AS AVERAGE_ENG_MARKS FROM NEW_STUDENTS;
SELECT SUM(ENG_MARKS) AS TOTAL_ENG_MARKS FROM NEW_STUDENTS;

SELECT COUNT(MATH_MARKS) AS TOTAL_STUDENTS FROM NEW_STUDENTS;
SELECT AVG(MATH_MARKS) AS AVERAGE_MATH_MARKS FROM NEW_STUDENTS;
SELECT SUM(MATH_MARKS) AS TOTAL_MATH_MARKS FROM NEW_STUDENTS;

SELECT COUNT(HINDI_MARKS) AS TOTAL_STUDENTS FROM NEW_STUDENTS;
SELECT AVG(HINDI_MARKS) AS AVERAGE_HINDI_MARKS FROM NEW_STUDENTS;
SELECT SUM(HINDI_MARKS) AS TOTAL_HINDI_MARKS FROM NEW_STUDENTS;

SELECT COUNT(SS_MARKS) AS TOTAL_STUDENTS FROM NEW_STUDENTS;
SELECT AVG(SS_MARKS) AS AVERAGE_SS_MARKS FROM NEW_STUDENTS;
SELECT SUM(SS_MARKS) AS TOTAL_SS_MARKS FROM NEW_STUDENTS;

SELECT COUNT(SCIENCE_MARKS) AS TOTAL_STUDENTS FROM NEW_STUDENTS;
SELECT AVG(SCIENCE_MARKS) AS AVERAGE_SCIENCE_MARKS FROM NEW_STUDENTS;
SELECT SUM(SCIENCE_MARKS) AS TOTAL_SCIENCE_MARKS FROM NEW_STUDENTS;