
name = input("What is your name? ")
nickname = input("What is your nickname? ")
dob = input("What is your date of birth? ")
fav_color = input("What is your favorite color? ")
hobby = input("What is your hobby? ")
best_friend = input("Who is your best friend? ")
dream = input("What is your biggest dream? ")
message = input("Write a message for your friends: ")

print("\n--- Slam Book Entry ---")
print(f"Name: {name}")
print(f"Nickname: {nickname}")
print(f"Date of Birth: {dob}")
print(f"Favorite Color: {fav_color}")
print(f"Hobby: {hobby}")
print(f"Best Friend: {best_friend}")
print(f"Biggest Dream: {dream}")
print(f"Message for Friends: {message}")