CREATE TABLE IF NOT EXISTS STUDENTS (
    ROLL_NUMBER INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    AGE INTEGER,
    PHONE TEXT,
    ADDRESS TEXT
);

INSERT INTO STUDENTS (ROLL_NUMBER, NAME, AGE ,PHONE, ADDRESS) VALUES
('1' , 'RAM','DELHI','*********','18'),
('2' , 'SHYAM','MUMBAI','*********','18'),
('3' , 'RAHUL','KOLKATA','*********','20'),
('4' , 'SUJIT','DELHI','*********','20'),
('5' , 'RAMESH','BANGALORE','*********','18'),

('6', 'DAKSH','PUNE','*********','18');

SELECT * FROM STUDENTS;
SELECT * FROM STUDENTS WHERE AGE = 18 AND ADDRESS = 'DELHI';
SELECT * FROM STUDENTS WHERE AGE = 18 OR NAME = 'RAM';
SELECT * FROM STUDENTS WHERE NAME = 'RAM' OR NAME = 'SUJIT';
SELECT * FROM STUDENTS WHERE NAME = 'RAM' OR AGE = 20;
SELECT * FROM STUDENTS WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');
