print("HELLO! CAN YOU GUESS THAT THE CODE BELOW IS RELATIONAL OR NON_RELATIONAL DATASET ?")

int = int(input( " PLEASE ENTER YOUR GUESS:"))

if int == 1:
    print("CONGRATS! YOU ARE CORRECT THIS IS A NON_RELATIONAL DATASET")

elif int == 2:
    print("SORRY! YOU ARE WRONG THIS IS A RELATIONAL DATASET")