CREATE TABLE EMPLOYEES (
S.NO TEXT PRIMARY KEY,
MONEY EARNED BY EMPLOYEES INTEGER,
NAME OF THE EMPLOYEE TEXT,
);

INSERT INTO EMPLOYEES ( S.NO , MONEY EARNED BY EMPLOYEE , NAME OF THE EMPLOYEE ) VALUES
( 'S1' , '24,209' , 'DAKSH' ),
( 'SS2' , '34,000' , 'SHORYA' ),
( 'SS3' , '45,000' , 'RAHUL' ),
( 'SS4' , '50,000' , 'ANUJ' ),
( 'SS5' , '60,000' , 'ADITYA' );

SELECT * FROM EMPLOYEES;
